[Project]
FileName=3varx.c
Name=3varc
Type=1
Ver=2
ObjFiles=
Includes=
Libs=
PrivateResource=3varc_private.rc
ResourceIncludes=
MakeIncludes=
Compiler=
CppCompiler=
Linker=
IsCpp=1
Icon=
ExeOutput=
ObjectOutput=
LogOutput=
LogOutputEnabled=0
OverrideOutput=0
OverrideOutputName=3varc.exe
HostApplication=
UseCustomMakefile=0
CustomMakefile=
CommandLine=
Folders=
IncludeVersionInfo=1
SupportXPThemes=0
CompilerSet=3
CompilerSettings=0000000100000000001000000
UnitCount=1

[VersionInfo]
Major=1
Minor=0
Release=0
Build=0
LanguageID=1033
CharsetID=1252
CompanyName=
FileVersion=1.0.0.0
FileDescription=Console interpreter for LuaGeek2412's language 3var.
InternalName=
LegalCopyright=
LegalTrademarks=
OriginalFilename=
ProductName=3varc
ProductVersion=1.0.0.0
AutoIncBuildNr=0
SyncProduct=1

[Unit1]
FileName=3varxc.c
CompileCpp=0
Folder=
Compile=1
Link=1
Priority=1000
OverrideBuildCmd=0
BuildCmd=$(CC) -c 3varc.cpp -o 3varc.o $(CFLAGS)

